name = 'Stelfox Special'
license = 'Proprietary License'
description = 'Private theme for my personal website'

homepage = 'https://github.com/sstelfox/stelfox.net'
demosite = 'https://stelfox.net'

tags = ['blog', 'personal']
features = ['mathjax', 'mermaid', 'posts']

[author]
name = 'Sam Stelfox'
homepage = 'https://stelfox.net'
