# This is a list of keys that identify the initial publication date of any
# particular page.
date:
  # This is my standard notes key which will be the key I eventually
  # migrate all my content to.
  - created_at
  # The default hugo key which a bunch of my legacy content is using
  - date
# This list of keys is used to automatically unpublish content after a certain
# page is no longer relevant. This does need a fresh build to actually perform
# the unpublishing but is great for things like events.
expiryDate:
  # These two are both the same, I've used them across various points in time
  # and not sure which one I prefer... Probably expires_at... Should
  # standardize on that...
  - expires_at
  - unpublish_at
lastmod:
  # I import content from different sources so while I would like to rely on my
  # git history for creation and update timestamps, they don't reflect reality.
  - updated_at
  - created_at
  - :git
# A "not before" date to allow posts to be written before deployment. This is
# separate from drafts in unpublished content. If no specific value is set for
# this, it falls back on information guaranteed to publish it right away.
publishDate:
  - published_at
  - created_at
  - date
  - :git
