title: "Sam Stelfox"
theme: "hello-friend-ng"

languageCode: "en-US"

clearDestinationDir: true
disableHugoGeneratorInject: true

paginate: 10
rssLimit: 10
#preserveTaxonomyNames: true

#taxonomies:
#  category: "categories"
#  series: "series"
#  tag: "tags"

#permalinks:
#  blog: "/blog/:year/:month/:slug/"
#  notes: "/notes/:slug"
#  page: "/:slug/"

#menu:
#  main:
#  - name: "Home"
#    url: "/"
#    weight: -100

#outputFormats:
#  RSS:
#    mediatype: "application/rss"
#    baseName: "atom"
