title: Sam Stelfox
theme: hello-friend-ng

languageCode: en-US

clearDestinationDir: true
disableHugoGeneratorInject: true

paginate: 10
rssLimit: 10
preserveTaxonomyNames: true

permalinks:
  blog: /blog/:year/:month/:slug/
  notes: /notes/:slug/
  page: /:slug/

params:
  contact:
    email: sam@stelfox.net
  subtitle: A simple place for my collected thoughts and notes.
#menu:
#  main:
#  - name: "Home"
#    url: "/"
#    weight: -100

#outputs:
#  home:
#    - html
#  section:
#    - html
#    - rss
#  taxonomy:
#    - html
#  RSS:
#    mediatype: "application/rss"
#    baseName: "atom"
