title: ./Sam_Stelfox.sh
description: Thoughts and notes of Sam Stelfox
copyright: Copyright © 2008-2024, Sam Stelfox, all rights reserved.

theme: hello-friend-ng
#theme: hugo-bearcub

# todo(sstelfox): my current design, while living in the themes directory relies
# on tailwind, postcss, and a few other things for now that live in the root
# directory. I'd like to keep it all together but I'm not sure that's posssible
# with this jank-ass generator.
#theme: stelfox-special

languageCode: en-US

# When building, removes files from the destination directory not found in
# static directories.
clearDestinationDir: true

# I'm really not a fan of these brag tags software like to do. It's not actually
# supporting the software just polluting my HTML.
disableHugoGeneratorInject: true

pagination:
  # Ten seems like a reasonable amount, I might want to drop the page values
  # down to 5 if I include the full post on my index pages...
  pagersize: 10

# Didn't think I'd want this, sometimes its nice to be able to throw a little
# levity into my posts. Doesn't hurt anything mind as well leave it on.
enableEmoji: true

# This allows git information to be used in the various timestamps for things
# like when the frontmatter doesn't contain a relevant date. These are not used
# as the default in my config, the specific priority is handled in the
# `frontmatter.yaml` config file.
enableGitInfo: true

# I generate this by hand and want to keep my own humourous musings though I
# suppose I could put them into a template or something for it.
enableRobotsTXT: false

# I don't think I'll ever have these in the slug's of my pages, but just to be
# sure I want to make sure they're stripped out to plain ASCII characters.
removePathAccents: true

permalinks:
  blog: /blog/:year/:month/:slug/
  notes: /notes/:slug/
  page: /:slug/
