goldmark:
  parser:
    # This allows text to naturally flow around images
    wrapStandAloneImageWithinParagraph: false

  renderHooks:
    image:
      enableDefault: true

  # Almost impercentable tweaks to the typography are not worth jacking up the
  # characters present in posts. These things are one of my biggest pet peeves
  # and I will not be party to them.
  typographer:
    disable: true
