highlight:
  # Enable displaying line numbers and allow them to be linkable directly
  linenos: true
  anchorlinenos: true

  # Disable inline style generation as it violates our CSP security policy,
  # we'll export the syntax styling as an independent CSS file that we can
  # hopefully combine into the general config...
  noclasses: true

  # Default is monokai, the hugo website claims to have a gallery but all but
  # two seem to be removed. It doesn't even include an example of the default
  # style so I'm not actually sure what my options are here... I'm using the
  # by-hand generation from my notes, so can tweak this style in that
  # stylesheet.
  style: github-dark

goldmark:
  # These are extensions that aren't officially part of the commonmark spec, I
  # may find some of these useful and certainly see no reason to leave them
  # disabled.
  extras:
    # Add support for striking through text using the ~~foo~~ syntax, turns it into
    # <del>foo</del>.
    delete:
      enable: true
    # Support for inserted text, syntax ++foo++, generates <ins>foo</ins>.
    insert:
      enable: true
    # Support for marked text, syntax ==foo=, generates <mark>foo</mark>.
    mark:
      enable: true
    # Support for subscript text, syntax H~2~), generates H<sub>2</sub>O.
    subscript:
      enable: true
    # Support for superscript text, syntax 1^st^, generates 1<sup>st</sup>.
    supscript:
      enable: true
  parser:
    # Drop any UTF-8 characters from autogenerated IDs, this helps keep links
    # clean from entity encoded characters in URLs.
    autoHeadingIDType: github-ascii

    # Image elements without adjacent content will be wrapped _within_ a `p`
    # element when rendered which is how most markdown renderers behave. Should
    # apparently be set to false if using a custom image render hook to turn
    # these into figure elements or the like.
    #
    # A separate part of the hugo documentation (https://gohugo.io/content-management/markdown-attributes/#standalone-images)
    # gave me an alternate definition for what this might do which may want me
    # to turn it off, but I currently don't use the extra attributes list
    # behavior.
    wrapStandAloneImageWithinParagraph: true

  # This allows me to use MathJAX correctly. Without these the content of these
  # delimters will also be treated as markdown and will be formatted
  # incorrectly, breaking the mathmatical syntax.
  passthrough:
    enable: true
    inline:
      - open: $
        close: $
    block:
      - open: $$
        close: $$

  renderHooks:
    image:
      enableDefault: true
    link:
      enableDefault: true

  # Almost impercentable tweaks to the typography are not worth jacking up the
  # characters present in posts. These things are one of my biggest pet peeves
  # and I will not be party to them.
  typographer:
    disable: true
