# The menu items that show up at the top of the site. The lower the number the
# further left the item will appear in the list. All things being equal, this
# order will appear in reverse order on the site due to the way the nav list is
# rendered into HTML.
main:
  - name: About
    pageRef: about
    weight: 30
  - name: Posts
    pageRef: blog
    weight: 20
  - name: Notes
    pageRef: notes
    weight: 20
