# The menu items that show up at the top of the site. The lower the number the
# further left the item will appear in the list.
main:
  - name: About
    pageRef: about
    weight: 10
  - name: Archive
    pageRef: blog
    weight: 20
  #- name: Knowledge Base
  #  pageRef: knowledge-base
  #  weight: 20
  - name: Notes
    pageRef: notes
    weight: 20
