# This is a big ol todo. I only want my blog posts and notes to have RSS feeds,
# but they should be distinct from each other. The outputs also allow custom
# outputs which can provide a search index, etc.
#
# https://gohugo.io/templates/output-formats/#output-formats-for-pages
#
# Definitions for custom formats live in a neighboring config file
# `outputFormats.yaml`. Things referenced in these lists may be defined there.
#
# This is a very poorly documented section in the hugo docs and has the ability
# to easily drop or mangle my content so I need to be careful making changes
# here.
home:
  - html
  - search_index
# Section cover all top level directories with a `_index.md` file. Section
# specific settings need to be defined in the section's specific frontmatter.
section:
  - html
  - rss
page:
  - html
taxonomy:
  - html
term:
  - html
rss:
  mediatype: application/rss
  baseName: atom
