author:
  email: sam@stelfox.net
  name: Sam Stelfox

# The officially correct key
subtitle: A simple place for my collected thoughts and notes.

# The key used by the hello-friend-ng instead of the officially correct subtitle key...
homeSubtitle: A simple place for my collected thoughts and notes.

#dateform: "Jan 2, 2006"
#dateformShort: "Jan 2"
#dateformNum: "2006-01-02"
#dateformNumTime: "2006-01-02 15:04"

#enableSharingButtons: false

#description: "Thoughts and notes of Sam Stelfox"
keywords: blog, programming, linux, systems, personal, rust, philosophy

logo:
  logotext: ./Sam_Stelfox.sh

#assets:
#  favicon: "favicon.ico"

#  customCSS: [ ]
#  customJS: [ ]
#  gopher: "" # used in 404 template ( Generator: https://gopherize.me )

copyright: "&copy; 2011 Sam Stelfox"

#info:
#  description: "Thoughts from a software engineer, systems architect and Linux gubernāre."
#  title404: "Nothing's here!"

#seo:
#  # Title Separator: - – — · • * ⋆ | ~ « » < >
#  titleSeparator: "•"

#settings:
#  # date & time format: https://golang.org/pkg/time/
#  dateFormat: "2006, Jan 02"
#  listDateFormat: "2006, Jan 02"
#  hideEntryNavigation: false
#  hideSocialMenu: false
#  showReadingTime: true

social:
  - name: github
    url: https://github.com/sstelfox
  - name: mastodon
    url: https://infosec.exchange/@pasties
  # No longer active on twitter
  #- name: twitter
  #  url: https://twitter.com/SamStelfox
  - name: email
    url: mailto:sam@stelfox.net
  - name: linkedin
    url: https://www.linkedin.com/in/samstelfox/
  # No longer active on keybase
  #- name: keybase
  #  url: https://keybase.io/sstelfox
