subtitle: A simple place for my collected thoughts and notes.
keywords: blog, programming, linux, systems, personal, rust, philosophy
favicon: favicon.ico

author: Sam Stelfox

# These are for the hello-friend-ng theme and should be removed once I no longer
# use it
homeSubtitle: A simple place for my collected thoughts and notes.
logo:
  logotext: ./Sam_Stelfox.sh

# Not sure where these came from
#settings:
#  # date & time format: https://golang.org/pkg/time/
#  hideEntryNavigation: false
#  hideSocialMenu: false
#  showReadingTime: true

social:
  - name: github
    url: https://github.com/sstelfox
  - name: mastodon
    url: https://infosec.exchange/@pasties
  - name: email
    url: mailto:sam@stelfox.net
  - name: linkedin
    url: https://www.linkedin.com/in/samstelfox/
