subtitle: A simple place for my collected thoughts and notes.
keywords: blog, programming, linux, systems, personal, rust, philosophy
favicon: favicon.ico

# Not sure if this one is used or the higher up one is...
author:
  email: sam@stelfox.net
  name: Sam Stelfox

# hello-friend-ng specific keys
#homeSubtitle: A simple place for my collected thoughts and notes.
#enableSharingButtons: false
#logo:
#  logotext: ./Sam_Stelfox.sh

# Possibly legacy keys
#dateform: "Jan 2, 2006"
#dateformShort: "Jan 2"
#dateformNum: "2006-01-02"
#dateformNumTime: "2006-01-02 15:04"

#description: "Thoughts and notes of Sam Stelfox"
#settings:
#  # date & time format: https://golang.org/pkg/time/
#  dateFormat: "2006, Jan 02"
#  listDateFormat: "2006, Jan 02"
#  hideEntryNavigation: false
#  hideSocialMenu: false
#  showReadingTime: true

social:
  - name: github
    url: https://github.com/sstelfox
  - name: mastodon
    url: https://infosec.exchange/@pasties
  # No longer active on twitter
  #- name: twitter
  #  url: https://twitter.com/SamStelfox
  - name: email
    url: mailto:sam@stelfox.net
  - name: linkedin
    url: https://www.linkedin.com/in/samstelfox/
  # No longer active on keybase
  #- name: keybase
  #  url: https://keybase.io/sstelfox
