# Turn off all of these various external integrations. I eventually do want a
# privacy preserving analytics and a lite youtube embedder but I can integrate
# plausible by hand and create a shortcode for youtube.
disqus:
  disable: true
googleAnalytics:
  disable: true
instagram:
  disable: true
twitter:
  disable: true
vimeo:
  disable: true
youTube:
  disable: true
