base_url = "https://stelfox.net"

title = "Sam Stelfox's Thoughts & Notes"
description = ""

default_language = "en"

build_search_index = true
compile_sass = true
generate_feed = true
minify_html = true

taxonomies = [
  { name = "tags" },
]

[markdown]
highlight_code = true
highlight_theme = "base16-ocean-dark"

[extra]
date_format = "%F"

# The number of tags that need to exist before it'll show up in the general tag
# listing
tag_threshold = 3

top_menu = [
  { url = "$BASE_URL", name = "Home" },
  { url = "$BASE_URL/about/", name = "About" },
  { url = "$BASE_URL/blog/", name = "Blog" },
  { url = "$BASE_URL/notes/", name = "Various Notes" },
]
