base_url = "https://stelfox.net"

title = "Sam Stelfox's Thoughts & Notes"
description = "Thought's from a software engineer, systems architect, and Linux gubernāre."

default_language = "en"

build_search_index = true
compile_sass = true
generate_feed = true
minify_html = false

taxonomies = [
  { name = "series" },
  { name = "tags" },
]

highlight_theme = "solarized-dark"

#[markdown]
#highlight_code = true
#highlight_theme = "base16-ocean-dark"

[extra]
author = "Sam Stelfox"
author_twitter = "@SamStelfox"

date_format = "%F"

#dark_theme_color = "black"
#light_theme_color = "white"

# The number of tags that need to exist before it'll show up in the general tag
# listing
tag_threshold = 3

site_menus = [
  { url = "/", name = "Home" },
  { url = "/about/", name = "About" },
  { url = "/blog/", name = "Blog" },
  { url = "/notes/", name = "Various Notes" },
  { url = "/projects/", name = "Projects" },
]
