headers:
  - for: /**
    values:
      # TODO: I want to figure out integrity hashes or splitting them out
      # without polluting my production environment with them before I put this
      # update in production to avoid CSP issues and maintain my integrity
      # protections.
      #Content-Security-Policy: script-src 'unsafe-inline' 'self' 127.0.0.1:8000
      Content-Security-Policy: script-src 'self'
      Referrer-Policy: strict-origin-when-cross-origin
      X-Content-Type-Options: nosniff
      X-Frame-Options: DENY
      X-XSS-Protection: 1; mode=block
