if $inputname != 'imfile' then {
  local7.*                                  action(type="omfile" file="/var/log/boot.log")
  cron.*                                    action(type="omfile" file="/var/log/cron")
  mail.*                                    action(type="omfile" file="/var/log/maillog")
  *.info;mail.none;authpriv.none;cron.none  action(type="omfile" file="/var/log/messages")
  authpriv.*                                action(type="omfile" file="/var/log/secure")
  uucp,news.crit                            action(type="omfile" file="/var/log/spooler")
  *.emerg                                   action(type="omusrmsg" users="*")
}
