*.* action(
  type="omfwd"
  target="logserver.example.tld"
  port="514"
  protocol="tcp"

  action.resumeretrycount="-1"

  queue.filename="log01"
  queue.size="1g"
  queue.type="LinkedList"
  queue.saveonshutdown="on"
)
