/var/log/remote/*/audit.log
/var/log/remote/*/boot.log
/var/log/remote/*/cron
/var/log/remote/*/maillog
/var/log/remote/*/messages
/var/log/remote/*/secure
/var/log/remote/*/spooler {
  # Keep three years worth of logs (52 weeks * 3 years)
  weekly
  rotate 52

  # If the file is missing, or empty just skip it and don't bother creating a
  # file if it's missing, rsyslog can handle it.
  missingok
  notifempty
  nocreate

  # Append the date to any rotated log files instead of an arbitrary number and
  # compress any rotated logs (with the exception of the most recent one).
  compress
  delaycompress
  dateext
  dateformat .%Y%m%d

  # When all the logs are done being rotated notify Rsyslog that it needs to
  # reopen all it's file descriptors.
  sharedscripts
  postrotate
    [ -s /var/run/syslogd.pid ] && kill -HUP $(cat /var/run/syslogd.pid) &> /dev/null || true
  endscript
}
