name = "Stelfox Dark"
license = "MIT"
description = "Minimal dark theme for stelfox.net"
homepage = "https://stelfox.net"
min_version = "0.110.0"

[author]
  name = "Sam Stelfox"
  homepage = "https://stelfox.net"
