set history=500
set nocompatible
autocmd! bufwritepost vimrc source ~/.vimrc
set modelines=10
set autoread
set scrolloff=5
set wildmenu
set ruler
set cmdheight=2
set nostartofline
set confirm
set pastetoggle=<F11>
nnoremap <C-L> :nohl<CR><C-L>
set shiftwidth=2 tabstop=2
set expandtab
set ai
set smarttab
set ignorecase
set hlsearch
set magic
set showmatch
set noerrorbells
set visualbell
set number
set hidden
syntax on
set ai
set encoding=utf8
try
  lang en_US
catch
endtry
set ffs=unix,dos,mac
set lbr
set laststatus=2
